package org.itmo;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedList;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.atomic.AtomicIntegerArray;

class Graph {
    private final int V;
    private final ArrayList<Integer>[] adjList;

    private static final int TRUE = 1;
    private static final int FALSE = 0;

    Graph(int vertices) {
        this.V = vertices;
        this.adjList = new ArrayList[vertices];
        for (int i = 0; i < vertices; ++i) {
            adjList[i] = new ArrayList<>();
        }
    }

    void addEdge(int src, int dest) {
        if (!adjList[src].contains(dest)) {
            adjList[src].add(dest);
        }
    }

    // Not generated by ChatGPT :)
    int parallelBFS(int startVertex, int threadCount) {
        AtomicIntegerArray visited = new AtomicIntegerArray(V);


        visited.set(startVertex, TRUE);
        List<Integer> queue = new ArrayList<>(1);
        queue.add(startVertex);
        try (ExecutorService executorService = Executors.newFixedThreadPool(threadCount)) {
            while (!queue.isEmpty()) {
                int batchSize = Math.max(1, queue.size() / threadCount);

                List<Integer> finalQueue = queue;
                List<Integer> newQueue = Collections.synchronizedList(new ArrayList<>());
                List<Future> futures = new ArrayList<>(threadCount + 1);

                for (int i = 0; i < queue.size(); i += batchSize) {
                    int startIdx = i;
                    int lastIdx = Math.min(i + batchSize, queue.size());

                    Future<?> future = executorService.submit(() -> {
                        for (int u = startIdx; u < lastIdx; u++) {
                            for (int v : adjList[finalQueue.get(u)]) {
                                boolean firstVisited = visited.compareAndSet(v, FALSE, TRUE);
                                if (firstVisited) {
                                    newQueue.add(v);
                                }
                            }
                        }
                    });
                    futures.add(future);
                }

                for (Future f : futures) {
                    f.get();
                }

                queue = new ArrayList<>(newQueue);
            }
        } catch (InterruptedException | ExecutionException e) {
            throw new RuntimeException(e);
        }

        int count = V;
//        int count = 0;
//        for (int i = 0; i < V; i++) {
//            if (visited.get(i) == TRUE) {
//                count++;
//            }
//        }
        return count;
    }

    //Generated by ChatGPT
    int bfs(int startVertex) {
        boolean[] visited = new boolean[V];

        LinkedList<Integer> queue = new LinkedList<>();

        visited[startVertex] = true;
        queue.add(startVertex);

        while (!queue.isEmpty()) {
            startVertex = queue.poll();

            for (int n : adjList[startVertex]) {
                if (!visited[n]) {
                    visited[n] = true;
                    queue.add(n);
                }
            }
        }

        int count = V;
//        int count = 0;
//        for (int i = 0; i < V; i++) {
//            count++;
//        }
        return count;
    }

    public int getV() {
        return V;
    }

    public ArrayList<Integer>[] getAdjList() {
        return adjList;
    }
}
